// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GBAT
DataFrame GBAT(DataFrame x, std::string id_col, std::string add_col, std::string third_col, std::string third_col_type);
RcppExport SEXP rGBAT16AB_GBAT(SEXP xSEXP, SEXP id_colSEXP, SEXP add_colSEXP, SEXP third_colSEXP, SEXP third_col_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type id_col(id_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type add_col(add_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type third_col(third_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type third_col_type(third_col_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(GBAT(x, id_col, add_col, third_col, third_col_type));
    return rcpp_result_gen;
END_RCPP
}
