# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GBAT <- function(x, id_col, add_col, boro_col) {
    .Call('rGBAT16AB_GBAT', PACKAGE = 'rGBAT16AB', x, id_col, add_col, boro_col)
}
