# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GBAT <- function(x, id_col, add_col, third_col, third_col_type = "boro_code") {
    .Call('rGBAT16AB_GBAT', PACKAGE = 'rGBAT16AB', x, id_col, add_col, third_col, third_col_type)
}
